name: Build and Restart EC2 Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  ssh-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands to deploy server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_ECE_SSH_KEY }}
          script: |
            cd package-rater
            git pull
            cd server
            yarn stop
            yarn build
            yarn start
            yarn pm2 status
