name: Build and Restart EC2 Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  ssh-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands to deploy server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_ECE_SSH_KEY }}
          script: |
            cd package-rater/server
            yarn stop
            cd ..
            git pull
            yarn
            yarn build
            cd server
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
            echo "NODE_ENV=prod" >> .env
            yarn start
            yarn pm2 status
